# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    #working_directory: ~/sheep-board-backend

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch}}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run: yarn install
      #- run: npm install

      - save_cache:
          key: yarn-cache-{{ .Branch}}-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run tests!
       - run: yarn test
  deploy:
    steps:
      - checkout
      - run:
        name: Deploy Master to Heroku
        command: |
          git push https://git.heroku.com/infinite-beach-93710.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
