# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-myapp-{{ .Branch }}-{{ checksum "package.json" }}
      # if cache for exact version of `project.clj` is not present then load any most recent one
          - v1-myapp-

      - run:
          name: Start Prisma server
          command: |
            npm install && npm install -g prisma
            docker-compose up -d
            cd prisma
            sleep 20
            prisma deploy

      - save_cache:
        key: - v1-myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - node_modules

      - run: npm run test
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
# filters:
#   branches:
#     only: master
